### ISSUE TITLE
Noslow

### ISSUE THREAD

**Issue by aoehakDoc** [Sigma-Skidder-Team/SigmaRemap#14]
eating a gapple or blocking with a sword while using noslow stops sprint in air

**Comment by AwayXD** [comment]
what noslow mode are you using

**Comment by aoehakDoc** [comment]
it happens on all modes

**Comment by AwayXD** [comment]
> it happens on all modes

We will add keepsprint to rebase, as of right now it is just a remap to make the code more readable.
