### ISSUE TITLE
jello portal display

### ISSUE THREAD

**Issue by aoehakDoc** [Sigma-Skidder-Team/SigmaRemap#15]
every time i leave a server and return to the multiplayer menu, the jello portal slider flips around, so that, for example, 1.21 would be on the left instead of right

**Comment by MarkGG8181** [comment]
sixth build?

**Comment by lamzvam** [comment]
> every time i leave a server and return to the multiplayer menu, the jello portal slider flips around, so that, for example, 1.21 would be on the left instead of right

that bug got fixed on dev build

**Comment by MichiHax** [comment]
> > every time i leave a server and return to the multiplayer menu, the jello portal slider flips around, so that, for example, 1.21 would be on the left instead of right
> 
> that bug got fixed on dev build

why do you not answer the thing i said in my issue
