### ISSUE TITLE
failed to launch

### ISSUE THREAD

**Issue by MichiHax** [Sigma-Skidder-Team/SigmaRemap#16]
this is the error, official minecraft launcher
Failed to download file.
Name: ViaBackwards-5.0.4.jar
URL: https://github.com/MarkGG8181/cloud/raw/refs/heads/main/sigma/5.0.4/ViaBackwards-5.0.4.jar
Filename on disk: ViaBackwards-5.0.4.jar
Path: C:\Users\my user\AppData\Roaming\.minecraft\libraries\com\mentalfrostbyte\ViaBackwards\5.0.4\ViaBackwards-5.0.4.jar
Exists: Nonexistent

**Comment by MarkGG8181** [comment]
Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries.

**Comment by MichiHax** [comment]
> Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6

wdym "set the main class" in the prelauncher

**Comment by axolot33l** [comment]
download doesnt work in build 6

**Comment by MarkGG8181** [comment]
> > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> 
> wdym "set the main class" in the prelauncher

If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”

**Comment by MichiHax** [comment]
> > > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> > 
> > 
> > wdym "set the main class" in the prelauncher
> 
> If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”

oh alr

**Comment by MarkGG8181** [comment]
> download doesnt work in build 6

If you don’t know how to use github then I can’t help you. It’s common knowledge to press on the SigmaRemapped.jar. That will instantly start the download smh.

**Comment by MichiHax** [comment]
> > > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> > 
> > 
> > wdym "set the main class" in the prelauncher
> 
> If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”

where do you have to put the prelauncher?

**Comment by MarkGG8181** [comment]
> > > > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> > > 
> > > 
> > > wdym "set the main class" in the prelauncher
> > 
> > 
> > If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”
> 
> where do you have to put the prelauncher?

.minecraft/versions/Sigma5/ <- if you don’t have that folder just create it.
And then download the jar and json from [here](https://github.com/Sigma-Skidder-Team/SigmaBootstrapper/releases/tag/1.0) and run through the mc launcher. Just make sure to set the java runtime to something other than minecraft’s official runtime.

**Comment by MichiHax** [comment]
> > > > > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> > > > 
> > > > 
> > > > wdym "set the main class" in the prelauncher
> > > 
> > > 
> > > If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”
> > 
> > 
> > where do you have to put the prelauncher?
> 
> .minecraft/versions/Sigma5/ <- if you don’t have that folder just create it. And then download the jar and json from [here](https://github.com/Sigma-Skidder-Team/SigmaBootstrapper/releases/tag/1.0) and run through the mc launcher. Just make sure to set the java runtime to something other than minecraft’s official runtime.

im confused.. is the bootstrapper update as well with the latest version?

**Comment by MarkGG8181** [comment]
> > > > > > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> > > > > 
> > > > > 
> > > > > wdym "set the main class" in the prelauncher
> > > > 
> > > > 
> > > > If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”
> > > 
> > > 
> > > where do you have to put the prelauncher?
> > 
> > 
> > .minecraft/versions/Sigma5/ <- if you don’t have that folder just create it. And then download the jar and json from [here](https://github.com/Sigma-Skidder-Team/SigmaBootstrapper/releases/tag/1.0) and run through the mc launcher. Just make sure to set the java runtime to something other than minecraft’s official runtime.
> 
> im confused.. is the bootstrapper update as well with the latest version?

It’s kinda confusing how sigma had it setup, but basically the bootstrapper downloads and runs the prelauncher which is a gui launcher where you can download and launch specific versions of Sigma. The prelauncher auto updates everything needed.

**Comment by MichiHax** [comment]
> > > > > > > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> > > > > > 
> > > > > > 
> > > > > > wdym "set the main class" in the prelauncher
> > > > > 
> > > > > 
> > > > > If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”
> > > > 
> > > > 
> > > > where do you have to put the prelauncher?
> > > 
> > > 
> > > .minecraft/versions/Sigma5/ <- if you don’t have that folder just create it. And then download the jar and json from [here](https://github.com/Sigma-Skidder-Team/SigmaBootstrapper/releases/tag/1.0) and run through the mc launcher. Just make sure to set the java runtime to something other than minecraft’s official runtime.
> > 
> > 
> > im confused.. is the bootstrapper update as well with the latest version?
> 
> It’s kinda confusing how sigma had it setup, but basically the bootstrapper downloads and runs the prelauncher which is a gui launcher where you can download and launch specific versions of Sigma. The prelauncher auto updates everything needed.

OHHH YEAHHH TYYYY

**Comment by MarkGG8181** [comment]
> > > > > > > > Update to the sixth build or use the prelauncher which auto updates. I updated the viaversion libraries. https://github.com/Sigma-Skidder-Team/SigmaRemap/releases/tag/1.6
> > > > > > > 
> > > > > > > 
> > > > > > > wdym "set the main class" in the prelauncher
> > > > > > 
> > > > > > 
> > > > > > If you are launching through the mc launcher you can ignore that comment, but if you are launching through the command prompt or making some launch script you have to set the main class with the argument “-cp”
> > > > > 
> > > > > 
> > > > > where do you have to put the prelauncher?
> > > > 
> > > > 
> > > > .minecraft/versions/Sigma5/ <- if you don’t have that folder just create it. And then download the jar and json from [here](https://github.com/Sigma-Skidder-Team/SigmaBootstrapper/releases/tag/1.0) and run through the mc launcher. Just make sure to set the java runtime to something other than minecraft’s official runtime.
> > > 
> > > 
> > > im confused.. is the bootstrapper update as well with the latest version?
> > 
> > 
> > It’s kinda confusing how sigma had it setup, but basically the bootstrapper downloads and runs the prelauncher which is a gui launcher where you can download and launch specific versions of Sigma. The prelauncher auto updates everything needed.
> 
> OHHH YEAHHH TYYYY

I will probably make a youtube tutorial on how to properly get Sigma working.

**Comment by MarkGG8181** [comment]
> this is the error, official minecraft launcher
> 
> Failed to download file.
> 
> Name: ViaBackwards-5.0.4.jar
> 
> URL: https://github.com/MarkGG8181/cloud/raw/refs/heads/main/sigma/5.0.4/ViaBackwards-5.0.4.jar
> 
> Filename on disk: ViaBackwards-5.0.4.jar
> 
> Path: C:\Users\my user\AppData\Roaming\.minecraft\libraries\com\mentalfrostbyte\ViaBackwards\5.0.4\ViaBackwards-5.0.4.jar
> 
> Exists: Nonexistent

Fixed in launcher and sixth build. I accidentally pasted the wrong url in the JSON.
