### ISSUE TITLE
Jello Portal STILL doesn't work

### ISSUE THREAD

**Issue by MichiHax** [Sigma-Skidder-Team/SigmaRemap#19]
I put it in 1.8.x and in 1.21 and hypixel still says i can't enter with 1.16, what??? i am using latest version btw.

**Comment by MarkGG8181** [comment]
Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.

**Comment by MichiHax** [comment]
> Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.

ohhh ok

**Comment by MichiHax** [comment]
> Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.

it still says i can't join in 1.16

**Comment by MarkGG8181** [comment]
> > Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.
> 
> it still says i can't join in 1.16

Try using this version and see if it also doesn't work:
![image](https://github.com/user-attachments/assets/3069bb51-bec5-4a26-9bdc-188da471afe7)

**Comment by MichiHax** [comment]
> > > Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.
> > 
> > 
> > it still says i can't join in 1.16
> 
> Try using this version and see if it also doesn't work: ![image](https://private-user-images.githubusercontent.com/86848614/380202069-3069bb51-bec5-4a26-9bdc-188da471afe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjYxNDgsIm5iZiI6MTcyOTg2NTg0OCwicGF0aCI6Ii84Njg0ODYxNC8zODAyMDIwNjktMzA2OWJiNTEtYmVjNS00YTI2LTliZGMtMTg4ZGE0NzFhZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE0MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMGZlODE2ZDdjYTA1OTkxZGRkZWNiYmFmOTUyZDY0ZDUxYjRjNjNkYjE5NmVhMDZmNmY5OTcyN2Y2ZGEwNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hsZ0S4nCVKtE5G1spq1f_6C19eNa2YoDIsELnleZeao)

i am using legacy launcher, because i have an alt but the alt manager doesn't work, and that version doesn't pop up. i'll try with sklauncher

**Comment by MichiHax** [comment]
> > > Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.
> > 
> > 
> > it still says i can't join in 1.16
> 
> Try using this version and see if it also doesn't work: ![image](https://private-user-images.githubusercontent.com/86848614/380202069-3069bb51-bec5-4a26-9bdc-188da471afe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjYxNDgsIm5iZiI6MTcyOTg2NTg0OCwicGF0aCI6Ii84Njg0ODYxNC8zODAyMDIwNjktMzA2OWJiNTEtYmVjNS00YTI2LTliZGMtMTg4ZGE0NzFhZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE0MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMGZlODE2ZDdjYTA1OTkxZGRkZWNiYmFmOTUyZDY0ZDUxYjRjNjNkYjE5NmVhMDZmNmY5OTcyN2Y2ZGEwNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hsZ0S4nCVKtE5G1spq1f_6C19eNa2YoDIsELnleZeao)

in sklauncher when opening it it just crashes, what??

**Comment by MichiHax** [comment]
> > > Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.
> > 
> > 
> > it still says i can't join in 1.16
> 
> Try using this version and see if it also doesn't work: ![image](https://private-user-images.githubusercontent.com/86848614/380202069-3069bb51-bec5-4a26-9bdc-188da471afe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzExMTUsIm5iZiI6MTcyOTkzMDgxNSwicGF0aCI6Ii84Njg0ODYxNC8zODAyMDIwNjktMzA2OWJiNTEtYmVjNS00YTI2LTliZGMtMTg4ZGE0NzFhZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA4MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2FmOGZjMDhmYzA4ZTMzYzExZjAyNDE3NTllNGE5N2I5MjNmZjhjODAwYzVjNTBiY2I3MThhZDk0NGRiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VVBYJaTdu-hLAnuWy2XGZWgjzuympQH5oWTKP3zCGew)

not even with that, it still doesn't work

**Comment by MarkGG8181** [comment]
> > > > Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.
> > > 
> > > 
> > > it still says i can't join in 1.16
> > 
> > 
> > Try using this version and see if it also doesn't work: ![image](https://private-user-images.githubusercontent.com/86848614/380202069-3069bb51-bec5-4a26-9bdc-188da471afe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzExMTUsIm5iZiI6MTcyOTkzMDgxNSwicGF0aCI6Ii84Njg0ODYxNC8zODAyMDIwNjktMzA2OWJiNTEtYmVjNS00YTI2LTliZGMtMTg4ZGE0NzFhZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA4MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2FmOGZjMDhmYzA4ZTMzYzExZjAyNDE3NTllNGE5N2I5MjNmZjhjODAwYzVjNTBiY2I3MThhZDk0NGRiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VVBYJaTdu-hLAnuWy2XGZWgjzuympQH5oWTKP3zCGew)
> 
> not even with that, it still doesn't work

Then I can’t help. Wait for Rebase to release.

**Comment by MichiHax** [comment]
> > > > > Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.
> > > > 
> > > > 
> > > > it still says i can't join in 1.16
> > > 
> > > 
> > > Try using this version and see if it also doesn't work: ![image](https://private-user-images.githubusercontent.com/86848614/380202069-3069bb51-bec5-4a26-9bdc-188da471afe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzExMTUsIm5iZiI6MTcyOTkzMDgxNSwicGF0aCI6Ii84Njg0ODYxNC8zODAyMDIwNjktMzA2OWJiNTEtYmVjNS00YTI2LTliZGMtMTg4ZGE0NzFhZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA4MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2FmOGZjMDhmYzA4ZTMzYzExZjAyNDE3NTllNGE5N2I5MjNmZjhjODAwYzVjNTBiY2I3MThhZDk0NGRiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VVBYJaTdu-hLAnuWy2XGZWgjzuympQH5oWTKP3zCGew)
> > 
> > 
> > not even with that, it still doesn't work
> 
> Then I can’t help. Wait for Rebase to release.

when would it be released

**Comment by MarkGG8181** [comment]
> > > > > > Jello portal versions only work from 1.16.4 up to 1.21, for Hypixel I suggest using 1.17.1.
> > > > > 
> > > > > 
> > > > > it still says i can't join in 1.16
> > > > 
> > > > 
> > > > Try using this version and see if it also doesn't work: ![image](https://private-user-images.githubusercontent.com/86848614/380202069-3069bb51-bec5-4a26-9bdc-188da471afe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzExMTUsIm5iZiI6MTcyOTkzMDgxNSwicGF0aCI6Ii84Njg0ODYxNC8zODAyMDIwNjktMzA2OWJiNTEtYmVjNS00YTI2LTliZGMtMTg4ZGE0NzFhZmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA4MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2FmOGZjMDhmYzA4ZTMzYzExZjAyNDE3NTllNGE5N2I5MjNmZjhjODAwYzVjNTBiY2I3MThhZDk0NGRiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VVBYJaTdu-hLAnuWy2XGZWgjzuympQH5oWTKP3zCGew)
> > > 
> > > 
> > > not even with that, it still doesn't work
> > 
> > 
> > Then I can’t help. Wait for Rebase to release.
> 
> when would it be released

Expect a beta somewhere next week.

**Comment by melodeu** [comment]
Wait until rebase beta for fix.
