### ISSUE TITLE
some showcase

### ISSUE THREAD

**Issue by Inkarro** [Sigma-Skidder-Team/SigmaRemap#2]
I spent half a month four months ago to fully deobfuscate Sigma 5.0b15, and the final product runs perfectly without any issues. There are many unfinished features and deprecated classes waiting for you to discover. Good luck! (btw, manually remapping the Minecraft part is really dumb; I relied on a custom analysis program to do the remapping automatically)
![image](https://github.com/user-attachments/assets/2c6c291f-73b9-4113-9e2c-500ec953b17c)
I also took the opportunity to update AltManager to support Microsoft login
![image](https://github.com/user-attachments/assets/975a910c-3ad5-483c-9d41-ab6553a01d2f)
and hypixel bypass
![image](https://github.com/user-attachments/assets/adbec175-8f86-42d6-af9d-0e736b8361f7)

**Comment by StormingMoon** [comment]
You dont have to anwser this if you dont want to but does any non custom analysis program work for this

**Comment by ImGGAAVVIINN** [comment]
Hey, I just want to say good job man this repo is very underrated, I stared it so now it has 4 stars :D
Also, how do I compile this? MCP?

**Comment by StormingMoon** [comment]
> Hey, I just want to say good job man this repo is very underrated, I stared it so now it has 4 stars :D Also, how do I compile this? MCP?

just use intelij clone the repo mark src/resources as resources in project structure 

Run normal vanilla mc 1.16 then copy the assets folder from .minecraft into intelij project folder of sigma remap the make a folder called run and paste it in there from there u can find stuff and make pull requests to the repo

**Comment by lamzvam** [comment]
> You dont have to anwser this if you dont want to but does any non custom analysis program work for this

it exists just for 1.8 and 1.12.2

**Comment by StormingMoon** [comment]
> > You dont have to anwser this if you dont want to but does any non custom analysis program work for this
> 
> it exists just for 1.8 and 1.12.2

ah bummer btw how is your fork going

**Comment by lamzvam** [comment]
> > > You dont have to anwser this if you dont want to but does any non custom analysis program work for this
> > 
> > 
> > it exists just for 1.8 and 1.12.2
> 
> ah bummer btw how is your fork going

im just using the sigmang base

**Comment by lamzvam** [comment]
> > > You dont have to anwser this if you dont want to but does any non custom analysis program work for this
> > 
> > 
> > it exists just for 1.8 and 1.12.2
> 
> ah bummer btw how is your fork going

do you have sigmaRemap jar, send it to me on my discord jazen0000 if you have it ill try something

**Comment by StormingMoon** [comment]
> > > > You dont have to anwser this if you dont want to but does any non custom analysis program work for this
> > > 
> > > 
> > > it exists just for 1.8 and 1.12.2
> > 
> > 
> > ah bummer btw how is your fork going
> 
> do you have sigmaRemap jar, send it to me on my discord jazen0000 if you have it ill try something

i added you on dc

**Comment by ColetteFan** [comment]
nigga fix Issue .minecraft/libraries/v1/SigmaRemapped/SigmaRemapped.jar
![Uploading image-5.png…]()
