### ISSUE TITLE
Sigma didn't launch as it was missing a file.

### ISSUE THREAD

**Issue by rllydaniel** [Sigma-Skidder-Team/SigmaRemap#20]
The original error was that the client was missing ViaBackwards-5.0.4.jar, which can be found at
\Users\[user]\AppData\Roaming\.minecraft\libraries\com\mentalfrostbyte\ViaBackwards\5.0.4
The file was missing for me, probably not the case forr others, but you can get it from https://github.com/MarkGG8181/cloud/blob/main/sigma/ViaBackwards-5.0.4.jar
This fixed the crashing issue for me.

**Comment by make-liuchenjun** [comment]
![b448895b20dbacfa6cf2234db38c1625](https://github.com/user-attachments/assets/04114087-4898-427a-a1de-f0a82b3e0460)
打不开

**Comment by MarkGG8181** [comment]
> ![b448895b20dbacfa6cf2234db38c1625](https://private-user-images.githubusercontent.com/159693051/380361666-04114087-4898-427a-a1de-f0a82b3e0460.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjgwMTQsIm5iZiI6MTcyOTkyNzcxNCwicGF0aCI6Ii8xNTk2OTMwNTEvMzgwMzYxNjY2LTA0MTE0MDg3LTQ4OTgtNDI3YS1hMWRlLWYwYTgyYjNlMDQ2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNzI4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWUyNjczOWUxNjMxZDhlZjAzZDZiMjM4N2QxODA4MGQ5MjllODdlYmZmNmJlNTMxYWIzNmJjMzEwY2ZmNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4UOALtLlyUFDsDPl66hevdOaHctKzfz17OMlqFIKqLU) 打不开

Your launcher is overriding the json file and trying to download from their own file host. Switch to a launcher that doesn’t force their own host.

**Comment by MarkGG8181** [comment]
> The original error was that the client was missing ViaBackwards-5.0.4.jar, which can be found at
> 
> \Users\[user]\AppData\Roaming\.minecraft\libraries\com\mentalfrostbyte\ViaBackwards\5.0.4
> 
> The file was missing for me, probably not the case forr others, but you can get it from https://github.com/MarkGG8181/cloud/blob/main/sigma/ViaBackwards-5.0.4.jar
> 
> This fixed the crashing issue for me.

Fixed in launcher and sixth build. JSON file had incorrect url to the viabackwards jar.
