### ISSUE TITLE
Sigma Client Cyrptominer

### ISSUE THREAD

**Issue by luhgarlicbread** [Sigma-Skidder-Team/SigmaRemap#21]
Soooo Sigma didn't have a cryptominer..?

**Comment by MarkGG8181** [comment]
> Soooo Sigma didn't have a cryptominer..?

No, that was made up by Nefarious @ intent because he was jealous that Sigma bypassed better on Hypixel than his clients. That made the Sigma devs quit as they lost most of their user base because of these accusations.

**Comment by luhgarlicbread** [comment]
> > Soooo Sigma didn't have a cryptominer..?
> 
> No, that was made up by Nefarious @ intent because he was jealous that Sigma bypassed better on Hypixel than his clients. That made the Sigma devs quit as they lost most of their user base because of these accusations.

This is the perfect response. Good to know! Yea I didn’t really believe that Sigma did have a miner but I wanted to be sure. Thanks!

**Comment by AwayXD** [comment]
> > > Soooo Sigma didn't have a cryptominer..?
> 
> > 
> 
> > No, that was made up by Nefarious @ intent because he was jealous that Sigma bypassed better on Hypixel than his clients. That made the Sigma devs quit as they lost most of their user base because of these accusations.
> 
> 
> 
> This is the perfect response. Good to know! Yea I didn’t really believe that Sigma did have a miner but I wanted to be sure. Thanks!

😁 glad we could help

**Comment by ImGGAAVVIINN** [comment]
Nefarious got his down fall pretty quickly after it so he get what he deserved a guess

**Comment by luhgarlicbread** [comment]
> Nefarious got his down fall pretty quickly after it so he get what he deserved a guess

God bless is all I can say.
