### ISSUE TITLE
so.. when is sigma rebase beta gonna be released?

### ISSUE THREAD

**Issue by MichiHax** [Sigma-Skidder-Team/SigmaRemap#23]
^ (just asking)

**Comment by melodeu** [comment]
Soon. i suppose we don't have an eta yet.

**Comment by DataM0del** [comment]
Hello zir, rebase has been released

**Comment by DataM0del** [comment]
Also this is an invalid issue since it's off topic / not related to Sigma Remap

**Comment by MichiHax** [comment]
> Hello zir, rebase has been released
I already quit mc so..

**Comment by MichiHax** [comment]
> Hello zir, rebase has been released

I already quit mc anyway so...
