### ISSUE TITLE
[feature request] extend jello portal to support version pass 1.16

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [Sigma-Skidder-Team/SigmaRemap#3]
From my understanding, sigma uses multiconnect, is it possible to upgrade and/or backport a later version to allow the client to connect to a wide range of servers? Since many servers don't run on 1.16 anymore.

**Comment by MarkGG8181** [comment]
I removed jello portal as it was really broken and unusable. There is a slight chance i’ll add viaversion, but it’s also really bad and will cause more anticheat flags than there is right now.

**Comment by lolbatch** [comment]
> I removed jello portal as it was really broken and unusable. There is a slight chance i’ll add viaversion, but it’s also really bad and will cause more anticheat flags than there is right now.

just add it, or skid it from sigma nextgen, this account is named sigma **skidder** team anyways but dont skid anything else 🙏

**Comment by ImGGAAVVIINN** [comment]
I could be wrong, but I remember next-gen lead dev removed the discord
server and the github repo because of a controvacy that I am not familiar
with

**Comment by MarkGG8181** [comment]
> I could be wrong, but I remember next-gen lead dev removed the discord server and the github repo because of a controvacy that I am not familiar with

controversy with what?🧐 skidding?

**Comment by ImGGAAVVIINN** [comment]
Yes the repo is gone 
https://github.com/FarisaAngeler1337/SigmaNextGen-Client-OpenSources/
