### ISSUE TITLE
1 month and still no rebase

### ISSUE THREAD

**Issue by MichiHax** [Sigma-Skidder-Team/SigmaRemap#30]
![caption](https://github.com/user-attachments/assets/88566645-4de1-46d5-b8b4-6fe68bb78644)

**Comment by melodeu** [comment]
There's no ETA currently, just sit tight and wait.

**Comment by DataM0del** [comment]
Also, someone in this org decided to private the rebase repo, I think it was public yesterday or 2 days ago.
Can't change that since I can't change the visibility settings of the repo.
