### ISSUE TITLE
Cannot resolve symbol 'Cleaner'

### ISSUE THREAD

**Issue by DataM0del** [Sigma-Skidder-Team/SigmaRemap#31]
probably :brain:
![image](https://github.com/user-attachments/assets/49342f72-8119-4811-a957-c0aec2bc2233)

**Comment by AwayXD** [comment]
Switch the project structure to Java 8 or 1.8 :)

**Comment by DataM0del** [comment]
It looks like it's working, I wonder if it didn't like that I was using GraalVM Community Edition.

**Comment by DataM0del** [comment]
It probably works because it's writing classes now.

**Comment by AwayXD** [comment]
No idea, glad it's working

**Comment by DataM0del** [comment]
![image](https://github.com/user-attachments/assets/f6d6337b-ffaf-42f5-80ec-0353957e2004)
imagine not enough memory smh (give moar ram!!!)

**Comment by AwayXD** [comment]
> ![image](https://github.com/user-attachments/assets/f6d6337b-ffaf-42f5-80ec-0353957e2004)
> 
> imagine not enough memory smh (give moar ram!!!)

Are you asking how or?

**Comment by DataM0del** [comment]
> > ![image](https://github.com/user-attachments/assets/f6d6337b-ffaf-42f5-80ec-0353957e2004)
> > 
> > imagine not enough memory smh (give moar ram!!!)
> 
> Are you asking how or?

It was a joke, ish. Can't add the XMX {}G flag because I'm on my phone because it's 11:01 PM CDT. Anyways, I have made some changes to this repo and will probably fork the project, change the origin remote to my fork's Git URL, push my changes, and open the PR.

**Comment by AwayXD** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/183248792/395954811-f6d6337b-ffaf-42f5-80ec-0353957e2004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjU4MTUsIm5iZiI6MTczNDMyNTUxNSwicGF0aCI6Ii8xODMyNDg3OTIvMzk1OTU0ODExLWY2ZDYzMzdiLWZmYWYtNDJmNS04MGVjLTAzNTM5NTdlMjAwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwNTA1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTc4MmE4M2RlODBmOGM0MDViYzQ0NjViOTQ4MDE2OGNhNTU4NzE1YjNmZTg3ZTQ5ZmY1ZjY5YTIxZDEwZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wHol5sk_68AGWv-KmdHJ45aVCU6uMxkUW6OF_cvVmgo)
> > > imagine not enough memory smh (give moar ram!!!)
> > 
> > 
> > Are you asking how or?
> 
> It was a joke, ish. Can't add the XMX {}G flag because I'm on my phone because it's 11:01 PM CDT. Anyways, I have made some changes to this repo and will probably fork the project, change the origin remote to my fork's Git URL, push my changes, and open the PR.

It isn't a xmx issue you just need to go to settings >compiler>allocated ram and change it to 2000

**Comment by DataM0del** [comment]
I just said that because I thought you'd do it through the compiler flags, and the XMX flag is what you use when you want to Change the memory for all JREs
