### ISSUE TITLE
Jello mode crashes (5.0.0 beta 24)

### ISSUE THREAD

**Issue by notamudkipiguess** [Sigma-Skidder-Team/SigmaRemap#34]
[crash.txt](https://github.com/user-attachments/files/18221586/crash.txt)

title^

-noverify, tested on UltimMC version 5 0.7.0

classic mode launches but u cant do anything (no tabgui, commands, clickgui)

**Comment by notamudkipiguess** [comment]
will try the sixth build

**Comment by MarkGG8181** [comment]
> [crash.txt](https://github.com/user-attachments/files/18221586/crash.txt)
> 
> title^
> 
> -noverify, tested on UltimMC version 5 0.7.0
> 
> classic mode launches but u cant do anything (no tabgui, commands, clickgui)

Looking at the crash report your client crashed due to DiscordRPC not being found. Please check if the jar for DiscordRPC exists inside .minecraft/libraries/com/mentalfrostbyte/java-discord-rpc/2.0.1-all/

**Comment by notamudkipiguess** [comment]
checked my libraries folder and theres no "mentalfrostbyte" folder there, where can i download it?

**Comment by notamudkipiguess** [comment]
https://github.com/Sigma-Skidder-Team/SigmaRemap/blob/main/libraries/java-discord-rpc-2.0.1-all.jar

should i try installing this and make the same path?

**Comment by MarkGG8181** [comment]
> checked my libraries folder and theres no "mentalfrostbyte" folder there, where can i download it?
> 
> (in the com folder theres no mentalfrostbyte folder)

That means your launcher is trying to download sigma libraries from their own repositories. This usually happens with unofficial launchers. You can try downloading the libraries manually, but that’s a hassle. I suggest trying Titan Launcher or SKLauncher.

**Comment by notamudkipiguess** [comment]
SKLauncher worked, thanks!
