### ISSUE TITLE
FIX SPRINT ANIMATION

### ISSUE THREAD

**Issue by aoehakDoc** [Sigma-Skidder-Team/SigmaRemap#6]
only faces forwards

**Comment by MarkGG8181** [comment]
Please record a video of this. Not enough context to understand what you mean by this.

**Comment by aoehakDoc** [comment]
https://www.mediafire.com/file/uwmjiuroot0ng6t/--.mov/file

**Comment by lamzvam** [comment]
> only faces forwards

hi, the issue that you mentioned is bc the sprint was modified to be legit and not do omnisprint thing to the sides or back
