### ISSUE TITLE
Sigma 5.0.0 Beta 22 Fails To Launch

### ISSUE THREAD

**Issue by luhgarlicbread** [Sigma-Skidder-Team/SigmaRemap#7]
Using the latest build of SigmaRemap, when launching the client, upon selecting a choice in the Classic vs Jello selector, the game proceeds to instantly close. Shows the "Saving world" screen.
![image](https://github.com/user-attachments/assets/fc70c2e9-8024-4646-8831-8b19198d2cca)
[crash-2024-10-18_09.57.04-client.txt](https://github.com/user-attachments/files/17436579/crash-2024-10-18_09.57.04-client.txt)
I've attached my crash report.

**Comment by lamzvam** [comment]
try using sklauncher and if the issue persist try adding on jvm argument  -noverify

**Comment by luhgarlicbread** [comment]
> try using sklauncher and if the issue persist try adding on jvm argument -noverify

sklauncher worked idk if it was gonna work without -noverify but it worked with -noverifiy
