### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by MichiHax** [Sigma-Skidder-Team/SigmaRemap#8]
I'm saying this with the intention of improving, not hating!

1. ViaVersion or Jello Portal still doesn't work, like in the original Sigma. When I put it in 1.8.9 or in 1.21 it still joins in 1.16.4.

2. AutoBlock doesn't block. I mean I have vanilla autoblock enabled, and in anticheat-test.com it doesn't show as I am blocking, however when I block normally it does say.

3. I don't know if this is made on purpouse, but there's no animations in the client. As i said, I don't know if this is with the intention of improving performance.

**Comment by GatoV2** [comment]
1. We haven't implemented Jello Portal yet, it will come in a future version after we have done significant progress on the remap and fixing bugs.
2. idk wait for someone who knows to reply lmao
3. Which animations are you talking about?

**Comment by MarkGG8181** [comment]
That’s unfortunately @lamzvam’s build which we don’t have access to. We cannot help with bugs on his outdated base.

**Comment by lamzvam** [comment]
> I'm saying this with the intention of improving, not hating!
> 
> 1. ViaVersion or Jello Portal still doesn't work, like in the original Sigma. When I put it in 1.8.9 or in 1.21 it still joins in 1.16.4.
> 
> 2. AutoBlock doesn't block. I mean I have vanilla autoblock enabled, and in anticheat-test.com it doesn't show as I am blocking, however when I block normally it does say.
> 
> 3. I don't know if this is made on purpouse, but there's no animations in the client. As i said, I don't know if this is with the intention of improving performance.

hi, the sigma 5 betta 22 have just one bug from all you mentioned.
the jello portal works proppl and the issue with the killaura that doesnt block, yeah that true bfor the release i was recoding the autoblock thing to add real vanilla autoblock  so prob i broke something and thats is related with the animation issue , i fixed that issue yesterday on the dev build.
Anyway i ll try the released build to see if jello portal works, on dev build does.
The issues ll get fixed on t new release.
 Thanks for reporting that issue.

**Comment by MichiHax** [comment]
> 1. We haven't implemented Jello Portal yet, it will come in a future version after we have done significant progress on the remap and fixing bugs.
> 2. idk wait for someone who knows to reply lmao
> 3. Which animations are you talking about?

1. Oh alr

2. Lol ok

3. I am talking about in the jello menu, when you hover a button with the mouse, in the original there were animations, and in more places. Idc abt animations

**Comment by MichiHax** [comment]
> hi, the sigma 5 betta 22 have just one bug from all you mentioned.
> the jello portal works proppl and the issue with the killaura that doesnt block, yeah that true bfor the release i was recoding the autoblock thing to add real vanilla autoblock  so prob i broke something and thats is related with the animation issue , i fixed that issue yesterday on the dev build.
> Anyway i ll try the released build to see if jello portal works, on dev build does from 1.16 - 1.21, lower version still having issues on joining.
> The issues ll get fixed on t new release.
>  Thanks for reporting that issue.

I am saying the autoblock thing because vanilla autoblock with no noslow bypassed hypixel and winned hvhs. (Yes i saw it in the heist hacks vid) and, if it is not possible to bring back the original one, at least try to recreate the original or something.
No problem for adding the issue, i really wanted to cheat in hypixel with sigma but they blocked 1.16 from joining, so..

**Comment by lamzvam** [comment]
> > hi, the sigma 5 betta 22 have just one bug from all you mentioned.
> > the jello portal works proppl and the issue with the killaura that doesnt block, yeah that true bfor the release i was recoding the autoblock thing to add real vanilla autoblock  so prob i broke something and thats is related with the animation issue , i fixed that issue yesterday on the dev build.
> > Anyway i ll try the released build to see if jello portal works, on dev build does from 1.16 - 1.21, lower version still having issues on joining.
> > The issues ll get fixed on t new release.
> >  Thanks for reporting that issue.
> 
> I am saying the autoblock thing because vanilla autoblock with no noslow bypassed hypixel and winned hvhs. (Yes i saw it in the heist hacks vid) and, if it is not possible to bring back the original one, at least try to recreate the original or something.
> No problem for adding the issue, i really wanted to cheat in hypixel with sigma (sounds dumb but it worked) but they blocked 1.16 from joining, so..

interesting, but that autoblock ll get back with other name bc wasnt really vanilla autoblock and the one i added is the real one , what version you can join on hypixel? bc viaversion still doesnt work with 1.8-1.15

**Comment by MichiHax** [comment]
> interesting, but that autoblock ll get back with other name bc wasnt really vanilla autoblock and the one i added is the real one , what version you can join on hypixel? bc viaversion still doesnt work with 1.8-1.15

I think you can join hypixel from 1.7 - 1.21, except 1.16.x. If you readd the autoblock, i can test it and say if it works in hypixel and then name it hypixel, but dont add an integrated noslow (when you are blocking it slows down) because noslow will flag on hypixel (obv)

**Comment by lamzvam** [comment]
> > interesting, but that autoblock ll get back with other name bc wasnt really vanilla autoblock and the one i added is the real one , what version you can join on hypixel? bc viaversion still doesnt work with 1.8-1.15
> 
> I think you can join hypixel from 1.7 - 1.21, except 1.16.x. If you readd the autoblock, i can test it and say if it works in hypixel and then name it hypixel, but dont add an integrated noslow (when you are blocking it slows down) because noslow will flag on hypixel (obv)

the autoblock was added back as Basic3 and i was testing on hypixel and it works but the noslow its releasing the sword

**Comment by lamzvam** [comment]
> > the autoblock was added back as Basic3 and i was testing on hypixel and it works but the noslow its releasing the sword
> 
> With no noslow, it worked in hypixel (i tested with original sigma some months ago) so, if that works, now only fix the jello portal thing and it would be fine
> 
> 

yes it worked i have some clips https://streamable.com/hfjcj3

**Comment by MichiHax** [comment]
> yes it worked i have some clips https://streamable.com/hfjcj3
oh nice! when can you release it with the autoblock and the jello portal fixed?
